### ISSUE TITLE
Vinyl files should be cloned.

### ISSUE THREAD

**Issue by mocanu-razvan** [danielhusar/gulp-save#3]
Hi,

First of all, congratulations for a very useful plugin.

I have used it and ran into some problems. I think it could be improved if the cached vinyl files are _cloned_ using the [clone](https://github.com/wearefractal/vinyl#cloneopt) method instead of passing the file to the constructor.

The problem with the current implementation is that properties are shared between the original vinyl files and the cached ones. Whenever you copy the file somewhere, the cached files change as well.

This behaviour is unexpected.

Thank you.

**Comment by danielhusar** [comment]
Hey,

thanks for reporting this.
Is this what you looking for? 

https://github.com/danielhusar/gulp-save/pull/4

**Comment by mocanu-razvan** [comment]
Hi,

Great! This is what I was looking for.

It will be slower, because now `contents` will be copied as well. There is an option to prevent that from happening in the `clone` method's options, but it's not safe. I can imagine some use cases that modify the file's contents and that gets reflected in the cache which would be again unexpected.

A nice way would be to be able to control that from the `gulp-save` plugin, as an option passed when constructing the cache, so that speed is gained for use cases where the contents do not matter.

What do you think?

**Comment by danielhusar** [comment]
Yeah I can pass through options that goes clone function, sounds good to me as well :)

**Comment by danielhusar** [comment]
Fixed now in 1.1.0

**Comment by mocanu-razvan** [comment]
Thanks for the quick fix.
