### ISSUE TITLE
Always create stores

### ISSUE THREAD

**Issue by MaxArt2501** [danielhusar/gulp-save#8]
At the moment, the plugin creates a store only when the first file is passed through the stream.
This leads to missing stores when the stream is empty for some reason, so `restore` won't find the store.

Thanks to #6 now this can be caught and dealt with, but would it be a problem to create the store right away, instead of waiting for the first file to be passed?

**Comment by danielhusar** [comment]
Yeah it could :) I can add you as a collaborator to this project if you wants to :)

**Comment by MaxArt2501** [comment]
Oh, that would ease the development of any idea that could come to my silly mind :)
Thanks!

**Comment by danielhusar** [comment]
Cool, I added you both here and on npm :)
